# -*- coding: utf-8 -*-
"""Análise perfil_cliente.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gFiEN2Id7G1tbD-DSYYNevfAgCc9E8D0
"""

# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python utilizada nesse projeto:', python_version())

"""#**RELATÓRIO ANÁLISE DE CLIENTES PARA CAMPANHA DE MARKETING**

O objetivo da classificação é prever se o cliente irá subscrever(sim ou não) um depósito a prazo!
"""

#instalando pacote pandas profiling para gerar o relatório
!pip install pandas-profiling

#importando demais pacotes
import pandas as pd
from pandas_profiling import ProfileReport

#importando dataset
df = pd.read_csv('/content/bank-full.csv', delimiter= ';')

"""Link do dataset: https://archive.ics.uci.edu/ml/datasets/bank+marketing"""

#Verificar as primeiras linhas do dataset
df.head()

#Estatísticas variáveis contínuas
df.describe()

##Pandas Profiling Relatório
from pandas_profiling import ProfileReport
profile = ProfileReport(df, title="Relatório base de clientes", html={'style':{'full_width':True}})
profile.to_notebook_iframe()
profile.to_file(output_file="Relatório base de clientes")